csv-email:
	notmuch show thread:00000000000045c2 > csv-email

invitation-email:
	notmuch show thread:00000000000029eb | grep -v unsubscribe > invitation-email

godi.html:
	wget -O godi.html http://sunlightfoundation.com/blog/2013/11/20/the-global-open-data-initiative-needs-your-input/
