csv-email:
	notmuch show thread:00000000000045c2 > csv-email

invitation-email:
	notmuch show thread:00000000000029eb | grep -v unsubscribe > invitation-email

godi.html:
	wget -O godi.html http://sunlightfoundation.com/blog/2013/11/20/the-global-open-data-initiative-needs-your-input/

forbes.html:
	wget -O forbes.html http://www.forbes.com/sites/bethsimonenoveck/2014/01/08/from-faith-based-to-evidence-based-the-open-data-500-and-understanding-how-open-data-helps-the-american-economy/
